baseurl = "https://degradka.github.io"
DefaultContentLanguage = "en"
title = 'degradka'
theme = 'beautifulhugo'
languageCode = "en-us"

[Params]
    subtitle = "Undereducated & over-ambitious electronics meddler."
    logo = "img/bio-logo.jpg"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = false
    readingTime = true
    socialShare = false
    showRelatedPosts = false
    hideAuthor = false

[Author]
    name = "degradka"
    website = "https://degradka.github.io"
    email = "degradka@gmail.com"
    github = "degradka"
    gitlab = "degradka"
    reddit = "degradka"
    itchio = "degradka"
    telegram = "degradka"
    mastodon = "https://mastodon.gamedev.place/@degradka"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3